#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# Trigger NotifIP on WAN-ish ifup events.
# Catches wan, wan6, wan2, wwan, wwan0, wan_4, wan_v6, mwan*…

[ "$ACTION" = "ifup" ] || exit 0

case "$INTERFACE" in
	wan*|wwan*|mwan*)
		(sleep 5; /usr/bin/notifip run) >/dev/null 2>&1 &
		;;
esac
